### PR TITLE
Use fieldnames method instead of accessing the field directly which fails on master.

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Thanks looks good.

Still some tests failing for nightly: https://travis-ci.org/bokeh/Bokeh.jl/jobs/64192727

Might as well fix them all at the same time.

**Comment by andreasnoack** [comment]
Ok. I've made some further changes so the tests are passing locally now. Haven't tried them on 0.3 yet some adjustments might be necessary.

**Comment by samuelcolvin** [comment]
I don't have much time to concentrate on this project right now but from my point of view this all looks good. @andreasnoack are you happy for me to merge this? would you like another release to incorporate these changes and the others since `v0.1.0`?

**Comment by andreasnoack** [comment]
Yes. I think it is ready for merge and it would be great with a new release such that it works on master. I really like the Bokeh plots.

**Pull request merged**
